<?php

namespace AppBundle\Repository;

/**
 * Show1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShowRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllByQuery($query){
        return $this->createQueryBuilder('s')
            ->where('LOWER(s.name) LIKE :query')
            ->setParameter('query','%'.$query.'%')
            ->getQuery()
            ->getResult()
            ;
    }
}
